/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcul.h"


void
calcul_1(char *host)
{
	CLIENT *clnt;
	void  *result_1;
	char *calcul_null_1_arg;
	reponse  *result_2;
	data  calcul_addition_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCUL, VERSION_UN, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = calcul_null_1((void*)&calcul_null_1_arg, clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = calcul_addition_1(&calcul_addition_1_arg, clnt);
	if (result_2 == (reponse *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}
CLIENT *clnt;

void test_addition_rpc(uint param1, uint param2)
{
  reponse *resultat;
  data parametre;
  parametre.arg1=param1;
  parametre.arg2=param2;
  printf("Appel de la fonction CALCUL_ADDITION avece les param %d %d\n",
	 param1,param2);
  resultat=calcul_addition_1(&parametre,clnt);
  printf("le resultat est %d\n",resultat->somme);
}

int
main (int argc, char *argv[])
{
	char *host;
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];

	clnt=clnt_create(host, CALCUL, VERSION_UN, "udp");
	test_addition_rpc(1,3);
	exit (0);
}
