// Skel class generated by rmic - DO NOT EDIT!

public final class IRemoteCalculette_Skel
    implements java.rmi.server.Skeleton
{
    private static final long interfaceHash = 266392L;
    
    private static final java.rmi.server.Operation[] operations = {
        
    };
    
    public java.rmi.server.Operation[] getOperations() {
        return ((java.rmi.server.Operation[]) operations.clone());
    }
    
    public void dispatch(java.rmi.Remote obj, java.rmi.server.RemoteCall call, int opnum, long hash) throws java.lang.Exception {
        if (opnum < 0) {
            {
                throw new java.rmi.server.SkeletonMismatchException("interface hash mismatch");
            }
        }
        else if (hash != interfaceHash) {
            throw new java.rmi.server.SkeletonMismatchException("interface hash mismatch");
        }
        
        IRemoteCalculette server = (IRemoteCalculette)obj;
        switch (opnum) {
        default:
            throw new java.rmi.UnmarshalException("invalid method number");
        }
    }
}
