// Stub class generated by rmic - DO NOT EDIT!

public final class IRemoteCalculette_Stub
    extends java.rmi.server.RemoteStub
    implements java.rmi.Remote
{
    private static final long serialVersionUID = 2L;
    
    private static final long interfaceHash = 266392L;
    
    private static boolean useNewInvoke;
    
    private static final java.rmi.server.Operation[] operations = {
        
    };
    
    
    static {
        try {
            java.rmi.server.RemoteRef.class.getMethod
                ("invoke", 
                 new java.lang.Class[] {
                    java.rmi.Remote.class, 
                    java.lang.reflect.Method.class, 
                    java.lang.Object[].class, long.class
                }
                 );
            useNewInvoke = true;
            
        }
        catch (java.lang.NoSuchMethodException e) {
            useNewInvoke = false;
        }
    }
    
    public IRemoteCalculette_Stub() {
        super();
    }
    public IRemoteCalculette_Stub(java.rmi.server.RemoteRef ref) {
        super(ref);
    }
    
}
