/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include<string.h>
#include "long.h"

int *
calcul_addition_1_svc(char **argp, struct svc_req *rqstp)
{
	static int  result;

	result=strlen(*argp);

	return &result;
}
