/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LONG_H_RPCGEN
#define _LONG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define LONGUEUR 0x20000001
#define VERSION_UN 1

#if defined(__STDC__) || defined(__cplusplus)
#define CALCUL_LONGUEUR 1
extern  int * calcul_longueur_1(char **, CLIENT *);
extern  int * calcul_longueur_1_svc(char **, struct svc_req *);
extern int longueur_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CALCUL_LONGUEUR 1
extern  int * calcul_longueur_1();
extern  int * calcul_longueur_1_svc();
extern int longueur_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LONG_H_RPCGEN */
