/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "long.h"


int 
longueur_1(char *host,char *param)
{
	CLIENT *clnt;
	int  *result_1;
	char * calcul_longueur_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, LONGUEUR, VERSION_UN, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	/* ICI C LE DEBUT DU RAJOUT */
	result_1 = calcul_longueur_1(&param, clnt);
	/*ICI C LA FIN */
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
	return *result_1;
}


int
main (int argc, char *argv[])
{
	char *host;
	/* ICI C LE DEBUT DU RAJOUT */
	int res;
	/* ICI C LA FIN */
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	/* ICI C LE DEBUT DU RAJOUT */
	res=longueur_1 (host,argv[2]);
	printf("resultat %d\n",res);
	/* ICI C LA FIN */
}
